spring:
  datasource:
    url: jdbc:h2:mem:mystreet;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  cors-origin: http://localhost:5173

server:
  port: ${PORT:8080}