spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  cors-origin: ${CORS_ORIGIN}

server:
  port: ${PORT:8080}